//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Order_ID { get; set; }
        public string Order_Name { get; set; }
        public string Order_Email { get; set; }
        public Nullable<int> Order_Soft_ID { get; set; }
        public Nullable<int> Order_Quantity { get; set; }
    
        public virtual SoftWares SoftWares { get; set; }
    }
}
