//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ID_Review { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Text { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> ID_Software { get; set; }
        public string User { get; set; }
    
        public virtual SoftWares SoftWares { get; set; }
    }
}
